#!/usr/bin/env bash
#   Parses Apache log files.
#   Group up visitors by IP and HTTP status code.
#   Prints the number of appearance, IP, and HTTP status code

awk '{ print $1 " " $9}' apache-access.log | sort | uniq -c | sort -rn
