#!/usr/bin/env bash
#This script iterate from 1 to 10 and prints a message
var=0
while [ $var -lt 10 ]
do
	var=$(( var + 1 ))
	if [ $var -eq 4 ] 
then
		echo "bad luck"
	elif [ $var -eq 8 ] 
then
		echo "good luck"
	else
		echo "Best School"
	fi
done
