#!/usr/bin/env bash
#   Prints numbers from 1 to 20 in with:
#   "bad luck from China" if 4th
#   "bad luck from Japan" if 9th
#   "bad luck from Italy" if 17th

var=1

while [ $var -le 20 ]
do
	echo "$var"
	case $var in
		"4") echo "bad luck from China";;
		"9") echo "bad luck from Japan";;
		"17") echo "bad luck from Italy";;
	esac
	(( var++ ))
done
